repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. See https://github.com/astral-sh/ruff-pre-commit/releases
    rev: v0.1.7
    hooks:
        # Run the linter.
        - id: ruff
          args: [--fix, --exit-non-zero-on-fix]
        # Run the formatter.
        - id: ruff-format